// Mocks generated by Mockito 5.4.4 from annotations
// in finq/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:finq/domain/entities/app_error.dart' as _i6;
import 'package:finq/domain/entities/no_params.dart' as _i7;
import 'package:finq/domain/repositories/application_repository.dart' as _i2;
import 'package:finq/domain/usecases/theme/get_preferred_theme.dart' as _i4;
import 'package:finq/domain/usecases/theme/update_theme.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApplicationRepository_0 extends _i1.SmartFake
    implements _i2.ApplicationRepository {
  _FakeApplicationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPreferredTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPreferredTheme extends _i1.Mock implements _i4.GetPreferredTheme {
  MockGetPreferredTheme() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApplicationRepository get appRepository => (super.noSuchMethod(
        Invocation.getter(#appRepository),
        returnValue: _FakeApplicationRepository_0(
          this,
          Invocation.getter(#appRepository),
        ),
      ) as _i2.ApplicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.AppError, String>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.AppError, String>>.value(
            _FakeEither_1<_i6.AppError, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AppError, String>>);
}

/// A class which mocks [UpdateTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTheme extends _i1.Mock implements _i8.UpdateTheme {
  MockUpdateTheme() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApplicationRepository get appRepository => (super.noSuchMethod(
        Invocation.getter(#appRepository),
        returnValue: _FakeApplicationRepository_0(
          this,
          Invocation.getter(#appRepository),
        ),
      ) as _i2.ApplicationRepository);

  @override
  _i5.Future<_i3.Either<_i6.AppError, void>> call(String? themeName) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [themeName],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.AppError, void>>.value(
            _FakeEither_1<_i6.AppError, void>(
          this,
          Invocation.method(
            #call,
            [themeName],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AppError, void>>);
}
